#!/usr/bin/perl
# xim (Xen Image Manager) uses LVM to manage Xen virtual machine images
# @author Jonathan Oxer <jon@ivt.com.au>
# @copyright 2006-2007 Internet Vision Technologies <www.ivt.com.au>
# @version 0.3
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# cpan install Text::CSV

use Switch;
use POSIX;
#use Text::CSV;
use strict;
use warnings;

# Set this to 1 to fake external command execution
our $dryrun = 0;
our $debug  = 0;
our $silent = 0;

####################################################################
####################################################################
# Figure out what command we've been called with. Initially, many of
# the commands will just be wrappers to xm and will pass arguments
# through unchanged.
if($ARGV[0])
{
	switch ($ARGV[0])
	{
		# Commands passed through to xm
		case "console"   { xm_wrapper() }
		case "create"    { xm_wrapper() }
		case "destroy"   { xm_wrapper() }
		case "list"      { xm_wrapper() }
		case "mem-set"   { xm_wrapper() }
		case "migrate"   { xm_wrapper() }
		case "pause"     { xm_wrapper() }
		case "reboot"    { xm_wrapper() }
		case "restore"   { xm_wrapper() }
		case "save"      { xm_wrapper() }
		case "shutdown"  { xm_wrapper() }
		case "top"       { xm_wrapper() }
		case "unpause"   { xm_wrapper() }
		case "vcpu-set"  { xm_wrapper() }

		# Native Xim operations
		case "survey"    { survey() }
		case "rename"    { xim_rename() }
		case "build"     { build() }
		case "demolish"  { demolish() }
		case "relocate"  { relocate() }
		case "propagate" { propagate() }
		case "duplicate" { duplicate() }

		# Direct access to internal functions for testing
		case "parse_vmlist"   { parse_vmlist() }
		case "survey_host"    { survey_host() }

		else             { usage(); exit }
	}
	exit;
}
else
{
	usage();
	exit;
}


####################################################################
# Wrap subcommands and pass them off to XM
sub xm_wrapper {
	# Glob all the command line arguments together for XM
	my $arguments;
	foreach (@ARGV) {
		$arguments .= " " . $_;
	}
	my $command = "xm" . $arguments;
#	print "$command\n";
	`$command`;
}


####################################################################
# Display internal usage info. Note that failed subcommands
# passed through to XM will result in XM's internal help being
# returned instead.
sub usage {
	print "Sorry, you need to specify a subcommand. Xim supports\n";
	print "the following standard xm subcommands:\n";
	print "   console\n";
	print "   create\n";
	print "   destroy\n";
	print "   list\n";
	print "   mem-set\n";
	print "   migrate\n";
	print "   pause\n";
	print "   reboot\n";
	print "   restore\n";
	print "   save\n";
	print "   shutdown\n";
	print "   top\n";
	print "   unpause\n";
	print "   vcpu-set\n";
	print "Xim also supports these extended subcommands:\n";
	print "   build <DomGroup> <DomName>               Create a new VM image and config\n";
	print "   rename <DomGroup> <DomName> <NewDomName> Rename an existing VM image\n";
	print "   demolish <DomGroup> <DomName>            Destroy a VM and delete all its files\n";
	print "   relocate <DomGroup> <DomName> <Host>     Migrate a running VM to another node\n";
	print "   propagate <DomGroup> <DomName> <Host>    Make a backup of a VM on another node\n";
	print "<DomGroup> is a way to arbitrarily group guest domains: each DomGroup is given\n";
	print "its own Volume Group in LVM and managed at a separate mount point.\n";
}


####################################################################
# Prompt the user for input and return the result or a default
sub prompt {
	my ($promptstring, $defaultvalue) = @_;
	if ($defaultvalue) {
		print $promptstring . "[" . $defaultvalue . "]";
	} else {
		print $promptstring . ": ";
	}
	$| = 1;
	$_ = <STDIN>;
	chomp;

	if ($defaultvalue) {
		return $_ ? $_ : $defaultvalue;
	} else {
		return $_;
	}
}



####################################################################
# Execute commands only if we're not in dry-run mode.
sub runcommand {
	my ($command, $output) = @_;
	my $result = "";

	# Display some text to the user
	if (($output) && ($silent ne 1)) {
		print " * " . $output . "\n";
	}

	# Print debug output
	if ($debug eq 1) {
		print "$command\n";
	}

	# Execute the requested command
	if ($dryrun ne 1) {
		$result = `$command`;
	}
	return ($result);
}

sub runcommand2 {
	my ($command, $output) = @_;
	my $result = "";

	# Display some text to the user
	if (($output) && ($silent ne 1)) {
		print " * " . $output . "\n";
	}

	# Print debug output
	if ($debug eq 1) {
		print "$command\n";
	}

	# Execute the requested command
	if ($dryrun ne 2) {
		$result = `$command`;
	}
	chomp($result);
	return ($result);
}


####################################################################
# Build a brand new VM
sub build {
	# Check if we have enough arguments
	if ( ($#ARGV + 1) eq 3 )
	{
#		print "Let's make a new VM!\n";
		my $imagegroup = $ARGV[1];
		my $imagename  = $ARGV[2];
		my $storagepath = "/" . $imagegroup;
#		print "$imagegroup\n";
#		print "$imagename\n";
#		print "$storagepath\n";
		# Prompt for user input for a bunch of settings for this VM
		my $vm_disksize  = prompt ("Size of disk image in GB:", "5");
		my $vm_swapsize  = prompt ("Size of swap space in MB:", "200");
		my $vm_ram       = prompt ("Size of RAM allocation in MB:", "192");
		my $vm_ipaddress = prompt ("IP address:", "221.133.213.254");
		my $vm_netmask   = prompt ("Netmask:", "255.255.255.0");
		my $vm_gateway   = prompt ("Gateway:", "221.133.213.1");
		my $vm_resolver  = prompt ("DNS server:", "202.91.207.135");

		# Figure out the MAC address based on the IP.
		# WARNING: This is dangerous at the moment because it doesn't check if the
		# generated MAC address actually conforms to requirements, and networking
		# can be broken if certain digits are used in specific locations. This needs
		# to be made more robust.
		# Split the dotted quads into array elements
		our @vm_mac = split(/\./, $vm_ipaddress);
		# Make sure each element is padded to three digits so we have a 12-digit number
		$vm_mac[0] = sprintf"%03d",$vm_mac[0];
		$vm_mac[1] = sprintf"%03d",$vm_mac[1];
		$vm_mac[2] = sprintf"%03d",$vm_mac[2];
		$vm_mac[3] = sprintf"%03d",$vm_mac[3];
		# Put the elements back together as one long string
		$main::vm_mac = join("", @vm_mac);
		# Chunk split the string into colon separated pairs of digits
		$main::vm_mac = substr($main::vm_mac, 0, 2).":".substr($main::vm_mac, 2, 2).":".substr($main::vm_mac, 4, 2).":".substr($main::vm_mac, 6, 2).":".substr($main::vm_mac, 8, 2).":".substr($main::vm_mac, 10, 2);

		# Show what values we're going to use
		print "Values for the new VM will be:\n";
		print " Name:       $imagename\n";
		print " Disk Size:  $vm_disksize GB\n";
		print " Swap Size:  $vm_swapsize MB\n";
		print " RAM Size:   $vm_ram MB\n";
		print " IP Address: $vm_ipaddress\n";
		print " Netmask:    $vm_netmask\n";
		print " Gateway:    $vm_gateway\n";
		print " DNS server: $vm_resolver\n";
		print " MAC addr:   $main::vm_mac\n";

		# Give one last chance to bail out before we start changing things
		my $continue  = prompt ("Continue?:", "Y");
		$continue =~ tr/A-Z/a-z/;
		if($continue ne "y")
		{
			print "OK, bailing out\n";
			exit 0;
		}

		# Execute the commands to create the VM image
		my $command = "";

		$command = "mkdir -p $storagepath/$imagename.d/mnt";
		runcommand ("$command", "Creating VM directory and mount point...");

		my $vm_disksizemb = $vm_disksize * 1000;
		$command = "lvcreate -L${vm_disksizemb}M -n ${imagename}-root $imagegroup";
		runcommand ("$command", "Creating the target root partition...");

		$command = "mkfs.ext3 /dev/${imagegroup}/${imagename}-root";
		runcommand ("$command", "Creating root filesystem on target root partition...");

		$command = "mount /dev/$imagegroup/${imagename}-root $storagepath/$imagename.d/mnt/";
		runcommand ("$command", "Mounting target root partition...");

		$command = "mount /dev/$imagegroup/guest $storagepath/guest/";
		runcommand ("$command", "Mounting source filesystem...");

		$command = "cp -a $storagepath/guest/* $storagepath/$imagename.d/mnt/";
		runcommand ("$command", "Copying source filesystem to target filesystem...");

		$command = "lvcreate -L{$vm_swapsize}M -n ${imagename}-swap $imagegroup";
		runcommand ("$command", "Creating the swap partition...");

		$command = "mkswap /dev/$imagegroup/${imagename}-swap";
		runcommand ("$command", "Creating swap filesystem...");

		# Create Xen conf
		print "Creating Xen config file...";
		my $vm_xenconfig = "#  -*- mode: python; -*-
kernel = \"/boot/vmlinuz-2.6.16-xen\"
ramdisk = \"/boot/initrd-2.6.16-xen.img\"
memory = $vm_ram
name = \"$imagename\"
vif = ['mac=$main::vm_mac,bridge=xenbr0']
disk = ['phy:$imagegroup/${imagename}-root,hda1,w','phy:$imagegroup/${imagename}-swap,hda2,w']
ip = \"$vm_ipaddress\"
netmask = \"$vm_netmask\"
gateway = \"$vm_gateway\"
hostname = \"$imagename\"
root = \"/dev/hda1 ro\"
extra = \"4\"";
		if($dryrun ne 1) {
			open (CONFIGFILE, ">$storagepath/$imagename.d/$imagename");
			print CONFIGFILE $vm_xenconfig;
			close (CONFIGFILE);
		}
		print "done\n";

		# Create interfaces
		print "Creating /etc/network/interfaces...";
		my $vm_netconfig = "# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
		address $vm_ipaddress
		netmask $vm_netmask
		gateway $vm_gateway
#        broadcast 1.0.1.255
#        dns-nameservers 192.168.0.1";
		if($dryrun ne 1) {
			open (CONFIGFILE, ">$storagepath/$imagename.d/mnt/etc/network/interfaces");
			print CONFIGFILE $vm_netconfig;
			close (CONFIGFILE);
		}
		print "done\n";

		# Create hostname
		print "Creating /etc/hostname...";
		my $vm_hostnameconfig = "$imagename";
		if($dryrun ne 1) {
			open (CONFIGFILE, ">$storagepath/$imagename.d/mnt/etc/hostname");
			print CONFIGFILE $vm_hostnameconfig;
			close (CONFIGFILE);
		}
		print "done\n";

		# Create hosts
		print "Creating /etc/hosts...";
		my $vm_hostsconfig = "127.0.0.1       localhost localhost.localdomain
127.0.0.1       $imagename
221.133.213.9	cache

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts";
		if($dryrun ne 1) {
			open (CONFIGFILE, ">$storagepath/$imagename.d/mnt/etc/hosts");
			print CONFIGFILE $vm_hostsconfig;
			close (CONFIGFILE);
		}
		print "done\n";

		# Create symlink for Xen
		#print "Creating config symlink...";
		#my $command = "ln -s /xen-images/$imagename/$imagename /etc/xen/$imagename";
		#print "c: $command\n";
		#`$command`;
		#print "done\n";

		# Unmount source and target
		$command = "sync; umount $storagepath/$imagename.d/mnt; umount $storagepath/guest";
		runcommand ("$command", "Unmounting source and target filesystems...");

	} else {
		print "Usage: xim build <imagegroup> <imagename>\n";
	}
}


####################################################################
# Demolish an existing VM
sub demolish {
	# Check if we have enough arguments
	if ( ( ($#ARGV + 1) eq 3 ) or ( ($#ARGV + 1) eq 4) )
	{
		my $imagegroup = $ARGV[1];
		my $imagename  = $ARGV[2];
		my $storagepath = "/" . $imagegroup;

		# Set the default node to localhost but allow the third argument to override it
		my $node = "localhost";
		if ( ($#ARGV + 1) eq 4 )
		{
			$node  = $ARGV[3];
		}

		print "Demolishing '${imagegroup}/${imagename}' on '${node}'\n";

		my $command = "";

		# Destroy the image in case it's running. Since we're nuking it anyway we
		# don't need to bring it down cleanly or wait politely
		$command = "xm destroy $imagename";
		runcommand ("$command", "Destroying image...");

		# lvremove root
		$command = "lvremove -f /dev/${imagegroup}/${imagename}-root";
		runcommand ("$command", "Removing root partition...");

		# Remove swap
		$command = "lvremove -f /dev/${imagegroup}/${imagename}-swap";
		runcommand ("$command", "Removing swap partition...");

		# Remove the config directory
		$command = "rm -Rf /${imagegroup}/${imagename}.d";
		runcommand ("$command", "Removing config directory...");
	} else {
		print "Usage: xim demolish <imagegroup> <imagename> [Host]\n";
		print "   'demolish' will remove all traces of a VM from a specific node, or from\n";
		print "   localhost if no host is specified: it destroys the running image if it\n";
		print "   exists, then removes the config directory and partitions.\n";
	}
}


####################################################################
# Rename an existing VM on the same node
sub xim_rename {
	# Check if we have enough arguments
	if ( ($#ARGV + 1) eq 4 )
	{
		my $imagegroup    = $ARGV[1];
		my $imagename     = $ARGV[2];
		my $newimagename  = $ARGV[3];
		my $storagepath = "/" . $imagegroup;

		print "Renaming '${imagegroup}/${imagename}' to '${imagegroup}/${newimagename}'\n";

		my $command = "";

		# Shut down the image in case it's running.
		$command = "xm shutdown $imagename";
		runcommand ("$command", "Shutting down image...");

		# Rename root
		$command = "lvrename /dev/${imagegroup}/${imagename}-root /dev/${imagegroup}/${newimagename}-root";
		runcommand ("$command", "Renaming root partition...");

		# Rename swap
		$command = "lvrename /dev/${imagegroup}/${imagename}-swap /dev/${imagegroup}/${newimagename}-swap";
		runcommand ("$command", "Renaming swap partition...");

		# Rename the config directory
		$command = "mv /${imagegroup}/${imagename}.d /${imagegroup}/${newimagename}.d";
		runcommand ("$command", "Renaming config directory...");

		$command = "mv /${imagegroup}/${newimagename}.d/${imagename} /${imagegroup}/${newimagename}.d/${newimagename}";
		runcommand ("$command", "Renaming config file...");

		$command = "sed -e \"s/${imagename}/${newimagename}/g\" ${storagepath}/${newimagename}.d/${newimagename} > ${storagepath}/${newimagename}.d/${newimagename}.temp";
		runcommand ("$command", "Modifying config file...");
		$command = "mv ${storagepath}/${newimagename}.d/${newimagename}.temp ${storagepath}/${newimagename}.d/${newimagename}";
		runcommand ("$command", "Moving config file...");

	} else {
		print "Usage: xim rename <imagegroup> <imagename> <newimagename>\n";
		print "   'rename' will convert an existing VM to a new name, including moving\n";
		print "   the config file and renaming LVM partitions. It first tries to shut down\n";
		print "   the VM to prevent damage if the partition is in use. It does not yet edit\n";
		print "   the actual config file or change any settings inside the VM such as IP\n";
		print "   address.\n";
	}
}


####################################################################
# Snapshot an existing VM to push it out to another node
sub relocate {
	print "Relocating an existing VM to another node\n";
	print "NOT YET IMPLEMENTED\n";
}


####################################################################
# Snapshot an existing VM to push it out to another node
sub propagate {
	# Check if we have enough arguments
	if ( ($#ARGV + 1) eq 4 )
	{
		my $imagegroup = $ARGV[1];
		my $imagename  = $ARGV[2];
		#my $sourcenode = $ARGV[3];
		my $targetnode = $ARGV[3];
		my $storagepath = "/".${imagegroup};
		print "Propagating '${imagegroup}/${imagename}' to '${targetnode}'\n";
		# lvcreate -L500M -s -n imagename-snapshot /dev/imagegroup/imagename-root

		my $command = "";

		$command = "modprobe dm-snapshot";
		runcommand ("$command", "Loading snapshot device-mapper kernel module on source node...");

		#$command = "ssh root\@${sourcenode} 'mkdir -p $storagepath/$imagename.d/snapshot'";
		$command = "mkdir -p $storagepath/$imagename.d/snapshot";
		runcommand ("$command", "Creating backup mount point on source node...");

		# We're hard-coding a disk image size here, which is bad. Need to check size of local partition
		my $vm_disksize = `lvdisplay /dev/${imagegroup}/${imagename}-root | grep "LV Size" | awk '\{print \$3\}'`;
		print "Unrounded: $vm_disksize\n";
		$vm_disksize = ceil($vm_disksize);
		print "Rounded: $vm_disksize\n";
		#my $vm_disksize = 25;
		my $vm_disksizemb = $vm_disksize * 1000;

		$command = "lvcreate -L50GB -s -n \"${imagename}-snapshot\" /dev/$imagegroup/${imagename}-root";
		runcommand ("$command", "Creating the snapshot partition on source node...");
		sleep 3;

		my $checkvalue = 1;
		#$command = "echo \$?";
		#$checkvalue = runcommand2 ("$command", "Checking snapshot creation...");
		print " * Checking snapshot creation...\n";
		$checkvalue = `echo $?`;
		#print "Command return value = $checkvalue\n";

		if ( $checkvalue == "0" )
		{
			$command = "mount /dev/${imagegroup}/${imagename}-snapshot $storagepath/$imagename.d/snapshot/";
			runcommand ("$command", "Mounting snapshot...");
#www.arsgeek.com/?p=650
			my $checkvalue = 1;
			#$command = "echo \$?";
			#$checkvalue = runcommand2 ("$command", "Checking snapshot mount successful...");
			print " * Checking snapshot mount successful...\n";
			$checkvalue = `echo $?`;
			#print "Command return value = $checkvalue\n";

			if ( $checkvalue == "0" )
			{
				$command = "ssh root\@${targetnode} mkdir -p ${storagepath}/${imagename}.d/mnt";
				runcommand ("$command", "Making VM directory and mount point on target node...");

				my $partitionexists = 0;
				$command = "ssh root\@${targetnode} lvscan | grep ${imagename}-root | wc -l";
				$partitionexists = runcommand2 ("$command", "Checking for VM root partition on target node...");
				#print "e: $partitionexists\n";

				#$partitionexists = 1;
				if ($partitionexists eq 0) {
					#print "creating!\n";
					$command = "ssh root\@${targetnode} lvcreate -L${vm_disksizemb}M -n \"${imagename}-root\" ${imagegroup}";
					runcommand ("$command", "Creating VM root partition on target node...");

					$command = "ssh root\@${targetnode} mkfs.ext3 /dev/${imagegroup}/${imagename}-root";
					runcommand ("$command", "Creating VM root filesystem on target node...");

					$command = "ssh root\@${targetnode} lvcreate -L200M -n \"${imagename}-swap\" ${imagegroup}";
					runcommand ("$command", "Creating VM swap partition on target node...");

					$command = "ssh root\@${targetnode} mkswap /dev/${imagegroup}/${imagename}-swap";
					runcommand ("$command", "Creating VM swap filesystem on target node...");
				}

				$command = "ssh root\@${targetnode} mount /dev/${imagegroup}/${imagename}-root ${storagepath}/${imagename}.d/mnt";
				runcommand ("$command", "Mounting VM root on target node...");

				$command = "nice rsync -e ssh --delete --delete-before -az --numeric-ids $storagepath/${imagename}.d/snapshot/ root\@${targetnode}:${storagepath}/${imagename}.d/mnt";
				#$command = "unison ssh://root\@${sourcenode}/$storagepath/${imagename}.d/snapshot ssh://root\@${targetnode}/${storagepath}/${imagename}.d/mnt -batch -silent -force ssh://root\@${sourcenode}/${storagepath}/${imagename}.d/snapshot";
				runcommand ("$command", "Syncing root filesystem to target node...");

				$command = "scp $storagepath/${imagename}.d/${imagename} root\@${targetnode}:${storagepath}/${imagename}.d/";
				runcommand ("$command", "Copying config file to target node...");

				$command = "umount ${storagepath}/${imagename}.d/snapshot";
				runcommand ("$command", "Unmounting VM snapshot on source node...");

				$command = "lvremove -f /dev/${imagegroup}/${imagename}-snapshot";
				runcommand ("$command", "Removing snapshot partition on source node...");

				$command = "ssh root\@${targetnode} \"umount ${storagepath}/${imagename}.d/mnt\"";
				runcommand ("$command", "Unmounting root filesystem on target node...");

#				$command = "";
#				runcommand ("$command", "...");


				# Check for a backup partition
				my $backuppartitionexists = 0;
				$command = "lvscan | grep ${imagename}-backup | wc -l";
				$backuppartitionexists = runcommand2 ("$command", "Checking for backup partition...");

				if ( $backuppartitionexists eq 1 )
				{
					my $vm_disksize = `lvdisplay /dev/${imagegroup}/${imagename}-backup | grep "LV Size" | awk '\{print \$3\}'`;
					print "Unrounded: $vm_disksize\n";
					$vm_disksize = ceil($vm_disksize);
					print "Rounded: $vm_disksize\n";
					#my $vm_disksize = 25;
					my $vm_disksizemb = $vm_disksize * 1000;

					$command = "lvcreate -L50GB -s -n \"${imagename}-snapshot\" /dev/$imagegroup/${imagename}-backup";
					runcommand ("$command", "Creating the snapshot partition on source node...");
					sleep 3;

					my $checkvalue = 1;
					#$command = "echo \$?";
					#$checkvalue = runcommand2 ("$command", "Checking snapshot creation...");
					print " * Checking snapshot creation...\n";
					$checkvalue = `echo $?`;
					#print "Command return value = $checkvalue\n";

					if ( $checkvalue == "0" )
					{
						$command = "mount /dev/${imagegroup}/${imagename}-snapshot $storagepath/$imagename.d/snapshot/";
						runcommand ("$command", "Mounting snapshot...");

						my $checkvalue = 1;
						#$command = "echo \$?";
						#$checkvalue = runcommand2 ("$command", "Checking snapshot mount successful...");
						print " * Checking snapshot mount successful...\n";
						$checkvalue = `echo $?`;
						#print "Command return value = $checkvalue\n";

						if ( $checkvalue == "0" )
						{
							$command = "ssh root\@${targetnode} mkdir -p ${storagepath}/${imagename}.d/mnt";
							runcommand ("$command", "Making VM directory and mount point on target node...");

							my $partitionexists = 0;
							$command = "ssh root\@${targetnode} lvscan | grep ${imagename}-backup | wc -l";
							$partitionexists = runcommand2 ("$command", "Checking for VM backup partition on target node...");
							#print "e: $partitionexists\n";

							#$partitionexists = 1;
							if ($partitionexists eq 0) {
								#print "creating!\n";
								$command = "ssh root\@${targetnode} lvcreate -L${vm_disksizemb}M -n \"${imagename}-backup\" ${imagegroup}";
								runcommand ("$command", "Creating VM backup partition on target node...");

								$command = "ssh root\@${targetnode} mkfs.ext3 /dev/${imagegroup}/${imagename}-backup";
								runcommand ("$command", "Creating VM backup filesystem on target node...");
							}

							$command = "ssh root\@${targetnode} mount /dev/${imagegroup}/${imagename}-backup ${storagepath}/${imagename}.d/mnt";
							runcommand ("$command", "Mounting VM backup partition on target node...");

							$command = "nice rsync -e ssh --delete --delete-before -az --numeric-ids $storagepath/${imagename}.d/snapshot/ root\@${targetnode}:${storagepath}/${imagename}.d/mnt";
							runcommand ("$command", "Syncing backup filesystem to target node...");

							$command = "umount ${storagepath}/${imagename}.d/snapshot";
							runcommand ("$command", "Unmounting VM snapshot on source node...");

							$command = "lvremove -f /dev/${imagegroup}/${imagename}-snapshot";
							runcommand ("$command", "Removing snapshot partition on source node...");

							$command = "ssh root\@${targetnode} \"umount ${storagepath}/${imagename}.d/mnt\"";
							runcommand ("$command", "Unmounting backup filesystem on target node...");
						}
						else
						{
							print "Snapshot mount failed... bailing\n";

							$command = "lvremove -f /dev/${imagegroup}/${imagename}-snapshot";
							runcommand ("$command", "Removing snapshot...");
						}
					}
					else
					{
						print "Couldn't create snapshot... bailing\n";
					}
				}
			}
			else
			{
				print "Snapshot mount failed... bailing\n";

				$command = "lvremove -f /dev/${imagegroup}/${imagename}-snapshot";
				runcommand ("$command", "Removing snapshot...");
			}
		}
		else
		{
			print "Couldn't create snapshot... bailing\n";
		}

	} else {
		print "Usage: xim propagate <imagegroup> <imagename> <Target Node>\n";
		print "   'propagate' copies the config and partitions of a VM to another\n";
		print "   node. If a copy already exists on the remote node it's updated.\n";
	}
}


####################################################################
# Snapshot an existing VM and duplicate it on the same node with a different name
sub duplicate {
	# Check if we have enough arguments
	if ( ($#ARGV + 1) eq 4 )
	{
		my $imagegroup = $ARGV[1];
		my $imagename  = $ARGV[2];
		#my $sourcenode = $ARGV[3];
		my $targetname = $ARGV[3];
		my $storagepath = "/".${imagegroup};
		print "Duplicating '${imagegroup}/${imagename}' to '${imagegroup}/${targetname}'\n";
		# lvcreate -L500M -s -n imagename-snapshot /dev/imagegroup/imagename-root

		my $command = "";

		$command = "modprobe dm-snapshot";
		runcommand ("$command", "Loading snapshot device-mapper kernel module...");

		#$command = "ssh root\@${sourcenode} 'mkdir -p $storagepath/$imagename.d/snapshot'";
		$command = "mkdir -p $storagepath/$imagename.d/snapshot";
		runcommand ("$command", "Creating source image mount point...");

		# We're hard-coding a disk image size here, which is bad. Need to check size of local partition
		my $vm_disksize = `lvdisplay /dev/${imagegroup}/${imagename}-root | grep "LV Size" | awk '\{print \$3\}'`;
		print "Unrounded: $vm_disksize\n";
		$vm_disksize = ceil($vm_disksize);
		print "Rounded: $vm_disksize\n";
		#my $vm_disksize = 25;
		my $vm_disksizemb = $vm_disksize * 1000;

		$command = "lvcreate -L50GB -s -n \"${imagename}-snapshot\" /dev/$imagegroup/${imagename}-root";
		runcommand ("$command", "Creating source image snapshot...");

		$command = "mount /dev/${imagegroup}/${imagename}-snapshot $storagepath/$imagename.d/snapshot/";
		runcommand ("$command", "Mounting source image snapshot...");
#www.arsgeek.com/?p=650
		
		$command = "mkdir -p ${storagepath}/${targetname}.d/mnt";
		runcommand ("$command", "Making target image directory and mount point...");

		my $partitionexists = 0;
		$command = "lvscan | grep ${targetname}-root | wc -l";
		$partitionexists = runcommand2 ("$command", "Checking for target image root partition...");
		#print "e: $partitionexists\n";

		#$partitionexists = 1;
		if ($partitionexists eq 0) {
			#print "creating!\n";
			$command = "lvcreate -L${vm_disksizemb}M -n \"${targetname}-root\" ${imagegroup}";
			runcommand ("$command", "Creating target image root partition...");

			$command = "mkfs.ext3 /dev/${imagegroup}/${targetname}-root";
			runcommand ("$command", "Creating target image root filesystem...");

			$command = "lvcreate -L200M -n \"${targetname}-swap\" ${imagegroup}";
			runcommand ("$command", "Creating target image swap partition...");

			$command = "mkswap /dev/${imagegroup}/${targetname}-swap";
			runcommand ("$command", "Creating target image swap filesystem...");
		}

		$command = "mount /dev/${imagegroup}/${targetname}-root ${storagepath}/${targetname}.d/mnt";
		runcommand ("$command", "Mounting target image root filesystem...");

		$command = "nice rsync --delete --delete-before -az --numeric-ids $storagepath/${imagename}.d/snapshot/ ${storagepath}/${targetname}.d/mnt";
		#$command = "unison ssh://root\@${sourcenode}/$storagepath/${imagename}.d/snapshot ssh://root\@${targetnode}/${storagepath}/${imagename}.d/mnt -batch -silent -force ssh://root\@${sourcenode}/${storagepath}/${imagename}.d/snapshot";
		runcommand ("$command", "Syncing root filesystem...");

		$command = "cp $storagepath/${imagename}.d/${imagename} ${storagepath}/${targetname}.d/${targetname}";
		runcommand ("$command", "Copying config file...");

		$command = "sed -e \"s/${imagename}/${targetname}/g\" ${storagepath}/${targetname}.d/${targetname} > ${storagepath}/${targetname}.d/${targetname}.temp";
		runcommand ("$command", "Modifying config file...");
		$command = "mv ${storagepath}/${targetname}.d/${targetname}.temp ${storagepath}/${targetname}.d/${targetname}";
		runcommand ("$command", "Moving config file...");

		$command = "umount ${storagepath}/${imagename}.d/snapshot";
		runcommand ("$command", "Unmounting source image snapshot...");

		$command = "lvremove -f /dev/${imagegroup}/${imagename}-snapshot";
		runcommand ("$command", "Removing source snapshot partition...");

		$command = "umount ${storagepath}/${targetname}.d/mnt";
		runcommand ("$command", "Unmounting target image root filesystem...");

#		$command = "";
#		runcommand ("$command", "...");

	} else {
		print "Usage: xim duplicate <imagegroup> <imagename> <targetname>\n";
		print "   'duplicate' copies the config and partitions of a VM to create\n";
		print "   a duplicate VM with a different name. If the target name already\n";
		print "   exists it's updated to match the target. This operation is\n";
		print "   useful for either making local backups of running VMs or copying\n";
		print "   an existing VM to run it under a different name.\n";
	}
}



####################################################################
sub parse_vmlist {
	my $vmlist_file = "/etc/xim/vmlist.conf";
	my @vmlist;
	my @vmdetails;
	open VMLIST, $vmlist_file or die $!;

	while (<VMLIST>)
	{
		s/#.*$//;	# Kill off comments
		s/^\s+//;	# Kill off leading spaces
		s/\s+$//;	# Kill off trailing spaces
		if ($_)
		{
			my ($host, $copies, $interval) = split(/s*,s*/); # Split out the three values for each host
			@vmdetails = ("$host", $copies, "$interval");
			push(@vmlist, @vmdetails);
			#print "val: $host | $copies | $interval |\n";
		}
	}

	close VMLIST;
	#print @vmlist;
	return @vmlist;
}



####################################################################
sub survey_host {
	my $ipaddress = shift(@_);
	my $command;
	my $output;
	my @imagelist;
	my $imageline;
	my $imagename;
	my $imagesize;

	$command = "ssh root\@${ipaddress} lvscan | grep '\\-root'";
	$output = runcommand ("$command", "Checking for existing root images...");
	@imagelist = split(/\n/, $output);
	foreach $imageline (@imagelist) {
		print "l: $imageline\n";
		# Extract the name of the VM and the image size
		if ( $imageline =~ m/(\w*)-root' \[(\d*\.\d* \w*)/ ) {
			$imagename = $1;
			$imagesize = $2;
			print "i: $imagename\n";
			print "s: $imagesize\n";
			
			$output .= "Name: $imagename\n";
		}
	}
	#print @imagelist;
	#print $output;

	$command = "ssh root\@${ipaddress} xm list | grep -v 'Domain-0' | grep -v 'Name'";
	$output = runcommand ("$command", "Checking for running VMs...");
	print $output;

	print "\n\n";
}


####################################################################
sub survey {
	# Read the list of hosts
	my $hostlist_file = "/etc/xim/hostlist.csv";

	my $csv = Text::CSV->new();
	open (CSV, "<", $hostlist_file) or die $!;
	
	while (<CSV>) {
		next if ($. == 1); # Skip the first row. FIXME: Should just skip all rows starting with '#'
		$csv->parse($_);
		my @columns = $csv->fields();
		#print "Host: $columns[0]\nIP: $columns[1]\n\n";
		my $hostname = $columns[0];
		my $ipaddress = $columns[1];
		print "Processing host '$hostname' at '$ipaddress':\n";
		survey_host("$ipaddress");
	}
}

